name: Simple Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - master # Adjust this to your repository's default branch (main or master)

# Permissions required for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Job to prepare site content and upload it as an artifact
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare Pages Content (only HTML)
      run: |
        mkdir public
        # Copy all HTML files from the repository root to the public directory
        # '|| true' ensures the command doesn't fail if no HTML files are found
        cp *.html public/ || true 

        # --- Debugging logs ---
        echo "--- Contents of public directory for upload ---"
        ls -R public/
        echo "-----------------------------------------------"
        
        # Check if the public directory is empty
        if [ -z "$(ls -A public/)" ]; then
          echo "Error: public directory is empty! No HTML content to upload."
          exit 1
        fi

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: './public' # Specify the prepared public directory

  # Job to deploy the artifact to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # This job runs only after the 'build' job completes successfully
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

